# Generated by Django 4.2.7 on 2023-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking_ticket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
