# Generated by Django 4.2.7 on 2023-12-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_ticket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
