# Generated by Django 4.2.7 on 2023-11-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcribedusers',
            name='subscription_payments',
            field=models.ManyToManyField(related_name='subscribed_users', to='subscription.subscriptionpayment'),
        ),
    ]
