# Generated by Django 4.2.7 on 2023-12-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subcribedusers_subscription_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='timestamps',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
