# Generated by Django 4.2.7 on 2023-12-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionpayment_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcribedusers',
            name='is_reneue',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
