# Generated by Django 4.2.7 on 2023-11-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventposting',
            old_name='CompletionStatus',
            new_name='completionStatus',
        ),
        migrations.RenameField(
            model_name='eventposting',
            old_name='Description',
            new_name='description',
        ),
    ]
