# Generated by Django 4.2.7 on 2023-11-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_eventreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
        migrations.AddField(
            model_name='eventreview',
            name='images',
            field=models.ManyToManyField(related_name='event_reviews', to='posts.image'),
        ),
    ]
