# Generated by Django 4.2.7 on 2024-12-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_country_customuser_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('super_user', 'Super User'), ('premium', 'Premium User')], default='normal', max_length=20),
        ),
    ]
